language: cpp

os:
  - linux
  - osx

compiler:
  - clang

git:
  depth: 1

cache: apt

notifications:
  irc: "chat.freenode.net#qgis-test"
  on_failure: change
  on_success: change
  skip_join: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/467e3aff72e344d1dae3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: never # default: never

addons:
  postgresql: "9.1"

before_install:
  - ./ci/travis/${TRAVIS_OS_NAME}/before_install.sh

install:
  - ./ci/travis/${TRAVIS_OS_NAME}/install.sh

before_script:
  - ./ci/travis/${TRAVIS_OS_NAME}/before_script.sh

script:
  - ./ci/travis/${TRAVIS_OS_NAME}/script.sh

